### ISSUE TITLE
Update PS4Debug

### ISSUE THREAD

**Issue by ghost** [Leeful/leeful.github.io#4]
GiantPluto updated his PS4Debug.bin file yesterday and fixed ASLR:
https://github.com/GiantPluto/ps4debug/releases/tag/1.2.1

**Comment by Leeful** [comment]
Thanks for the heads up. I knew there was something I forgot to do. LOL
I'll update it soon. :)

**Comment by Leeful** [comment]
updated ps4debug to v1.2.1 on 672v6 and hentest
