### ISSUE TITLE
HEN v2.1.3b (672v8) PSVR issues

### ISSUE THREAD

**Issue by ApophysX** [Leeful/leeful.github.io#8]
Hello,

test on a PS4 Pro, i load hen 2.1.3b and turn on the PSVR a error popsup (CE-40170-2)
And i can not connect tow Move Controllers to my ps4 (only one will work)

i reset my ps4 Pro, after bootsup (without hen)  i turn on the tow Move Controllers an the PSVR everything works. Now load up hen v2.1.3b and it still works.

**Comment by Leeful** [comment]
This is a known bug, it is mentioned here: https://github.com/Leeful/ps4-hen-vtx/releases/tag/2.1.3b
Hen 2.1.3b is just a beta test, not an official release.
